version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-runtime-dependencies:
        dependency-type: production
      go-development-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-runtime-dependencies:
        dependency-type: production
      frontend-development-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
