// Command gen-routes-manifest generates internal/api/routes_manifest.go from router.go.
//
//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	root := os.Getenv("HSERVER_ROOT")
	if root == "" {
		root = "."
	}
	routerPath := filepath.Join(root, "internal/api/router.go")
	outPath := filepath.Join(root, "internal/api/routes_manifest.go")

	routerSrc, err := os.ReadFile(routerPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read router.go: %v\n", err)
		os.Exit(1)
	}

	routes := extractRoutes(string(routerSrc))
	if len(routes) == 0 {
		fmt.Fprintln(os.Stderr, "no routes extracted from router.go")
		os.Exit(1)
	}

	sort.Slice(routes, func(i, j int) bool {
		if routes[i].path != routes[j].path {
			return routes[i].path < routes[j].path
		}
		return routes[i].method < routes[j].method
	})

	var buf bytes.Buffer
	buf.WriteString(header)
	for _, r := range routes {
		fmt.Fprintf(&buf, "\t\t{%q, %q, %s},\n", r.method, r.path, r.auth)
	}
	buf.WriteString(footer)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write manifest: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s (%d routes)\n", outPath, len(routes))
}

type routeEntry struct {
	method string
	path   string
	auth   string
}

var routeStartRe = regexp.MustCompile(`mux\.HandleFunc\("([A-Z]+) ([^"]+)"`)

func extractRoutes(src string) []routeEntry {
	var routes []routeEntry
	i := 0
	for {
		loc := routeStartRe.FindStringSubmatchIndex(src[i:])
		if loc == nil {
			break
		}
		start := i + loc[0]
		method := src[i+loc[2] : i+loc[3]]
		path := src[i+loc[4] : i+loc[5]]

		// SPA catch-all is not part of API contract manifest.
		if method == "GET" && path == "/" {
			i = start + loc[1] - loc[0]
			continue
		}

		handlerStart := start + strings.Index(src[start:], ",") + 1
		end, ok := findBalancedClose(src, handlerStart)
		if !ok {
			break
		}
		handler := src[handlerStart:end]
		routes = append(routes, routeEntry{
			method: method,
			path:   path,
			auth:   classifyAuth(method, handler),
		})
		i = end + 1
	}
	return routes
}

func findBalancedClose(src string, start int) (int, bool) {
	depth := 0
	for i := start; i < len(src); i++ {
		switch src[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return i, true
			}
		}
	}
	return 0, false
}

func classifyAuth(method, handler string) string {
	h := strings.Join(strings.Fields(handler), " ")
	switch {
	case strings.Contains(h, "handleInternalCron"),
		strings.Contains(h, "handleInternalDeployPreflight"):
		return "RouteInternalCron"
	case strings.Contains(h, "handleAgentHeartbeat"),
		strings.Contains(h, "handleAgentTaskPoll"),
		strings.Contains(h, "handleAgentTaskResult"),
		strings.Contains(h, "handleAgentTerminal"):
		return "RouteAgent"
	case strings.Contains(h, "withAuth"):
		if strings.Contains(h, "requireRole(RoleAdmin") {
			return "RouteAdmin"
		}
		if strings.Contains(h, "requireRole(RoleManager") {
			return "RouteManager"
		}
		return "RouteProtected"
	default:
		return "RoutePublic"
	}
}

const header = `package api

import "strings"

// Code generated by scripts/gen-routes-manifest; DO NOT EDIT.
// Regenerate: go generate ./internal/api/...  or  make gen-routes

// RouteAuth describes the authentication expectation for a registered route.
type RouteAuth string

const (
	RoutePublic       RouteAuth = "public"        // no JWT required
	RouteProtected    RouteAuth = "protected"     // JWT required (any role)
	RouteManager      RouteAuth = "manager"       // JWT + manager or admin role
	RouteAdmin        RouteAuth = "admin"         // JWT + admin role
	RouteAgent        RouteAuth = "agent"         // managed-node identity + agent bearer token
	RouteInternalCron RouteAuth = "internal_cron" // localhost + X-Cron-Secret
)

// RouteSpec is a contract entry for router integration tests.
type RouteSpec struct {
	Method string
	Path   string
	Auth   RouteAuth
}

// AllRoutes returns every route registered in router.go for contract testing.
func AllRoutes() []RouteSpec {
	return []RouteSpec{
`

const footer = `	}
}

// fillRoutePath substitutes mux path placeholders with safe sample values.
func fillRoutePath(path string) string {
	repl := []struct{ from, to string }{
		{"{filename}", "example.conf"},
		{"{version}", "8.4"},
		{"{domain}", "example.com"},
		{"{id}", "1"},
		{"{name}", "testdb"},
		{"{engine}", "postgresql"},
		{"{email}", "user@example.com"},
		{"{selector}", "default"},
		{"{number}", "1"},
		{"{key}", "memory_limit"},
		{"{zoneId}", "zone123"},
		{"{recordId}", "rec123"},
		{"{targetId}", "target1"},
		{"{jail}", "sshd"},
		{"{ip}", "203.0.113.1"},
		{"{action}", "restart"},
		{"{slug}", "main"},
		{"{pattern}", "spam.example"},
		{"{device}", "sda"},
	}
	for _, r := range repl {
		path = strings.ReplaceAll(path, r.from, r.to)
	}
	return path
}
`
